'use strict';

const { loadKnowledgeBase } = require('../compiler/load-knowledge-base');
const { INTERVIEW_ID, CATALOG_VERSION, BRANCHING_VERSION } = require('./utils');

function options(items) { return (items || []).map((item) => ({ value: item.id, label: item.name })); }
function choices(values) { return values.map(([value, label]) => ({ value, label })); }
function question(definition) {
  return {
    validation: {},
    options: [],
    dependencies: [],
    follow_up_question_ids: [],
    mapping_destination: null,
    ui: null,
    ...definition
  };
}

function getQuestionCatalog({ root }) {
  const knowledge = loadKnowledgeBase(root);
  const categories = [
    { id: 'discovery', title: 'Discovery', description: 'Set the business context, current presence, desired outcome, and design constraints.', order: 1 },
    { id: 'business', title: 'Business', description: 'Tell Calinium what the business is and where it is today.', order: 2 },
    { id: 'brand', title: 'Brand', description: 'Describe the brand’s purpose, character, and voice.', order: 3 },
    { id: 'audience', title: 'Target audience', description: 'Identify the customers and market position the storefront should serve.', order: 4 },
    { id: 'products', title: 'Products', description: 'Describe the catalog, delivery model, and product context.', order: 5 },
    { id: 'design', title: 'Design', description: 'Choose visual preferences without copying another storefront.', order: 6 },
    { id: 'brand_references', title: 'Brand references', description: 'Record inspiration and competitors separately; neither is a design-copying instruction.', order: 7 },
    { id: 'features', title: 'Features', description: 'Identify desired commerce and storefront capabilities.', order: 8 },
    { id: 'content', title: 'Content', description: 'Record approved brand assets, colours, typography, and source material.', order: 9 },
    { id: 'goals', title: 'Goals', description: 'Set the outcomes the future storefront should prioritize.', order: 10 }
  ];
  const questions = [
    question({ id: 'discovery_business_stage', category_id: 'discovery', title: 'Where is your business today?', description: 'This helps Calinium ask only the context that is relevant to the current stage.', answer_type: 'single_choice', required: true, options: choices([['idea', 'Idea'], ['preparing_to_launch', 'Preparing to launch'], ['newly_launched', 'Newly launched'], ['established_business', 'Established business'], ['existing_shopify_store', 'Existing Shopify store'], ['migrating_platform', 'Migrating platform'], ['redesigning_existing_store', 'Redesigning an existing store']]), mapping_destination: 'enrichment.discovery.business_stage' }),
    question({ id: 'discovery_has_existing_website', category_id: 'discovery', title: 'Do you currently have a website?', description: 'Calinium stores this context but does not fetch or analyse the site in this phase.', answer_type: 'single_choice', required: true, options: choices([['no_existing_website', 'No existing website'], ['yes_existing_website', 'Yes, an existing website']]), follow_up_question_ids: ['discovery_website_url', 'discovery_website_platform', 'discovery_website_live', 'discovery_website_preserve', 'discovery_website_improve', 'discovery_website_dislikes'], mapping_destination: 'enrichment.existing_presence.website.status' }),
    question({ id: 'discovery_website_url', category_id: 'discovery', title: 'What is the website URL?', description: 'Enter the complete URL. Calinium will retain it as a merchant-provided reference only.', answer_type: 'url', required: true, dependencies: [{ question_id: 'discovery_has_existing_website', operator: 'equals', value: 'yes_existing_website' }], mapping_destination: 'enrichment.existing_presence.website.url' }),
    question({ id: 'discovery_website_platform', category_id: 'discovery', title: 'Which platform does the website use?', description: 'Optional. Enter the platform only if you know it.', answer_type: 'text', required: false, validation: { max_length: 120 }, dependencies: [{ question_id: 'discovery_has_existing_website', operator: 'equals', value: 'yes_existing_website' }], mapping_destination: 'enrichment.existing_presence.website.platform' }),
    question({ id: 'discovery_website_live', category_id: 'discovery', title: 'Is the current website live?', description: 'This is stored as context and does not trigger a website connection.', answer_type: 'boolean', required: true, dependencies: [{ question_id: 'discovery_has_existing_website', operator: 'equals', value: 'yes_existing_website' }], mapping_destination: 'enrichment.existing_presence.website.is_live' }),
    question({ id: 'discovery_website_preserve', category_id: 'discovery', title: 'What should be preserved?', description: 'Optional tags for the elements that still work well.', answer_type: 'tags', required: false, validation: { max_items: 8, max_length: 120 }, dependencies: [{ question_id: 'discovery_has_existing_website', operator: 'equals', value: 'yes_existing_website' }], mapping_destination: 'enrichment.existing_presence.website.preserve' }),
    question({ id: 'discovery_website_improve', category_id: 'discovery', title: 'What should be improved?', description: 'Optional tags for the areas that need attention.', answer_type: 'tags', required: false, validation: { max_items: 8, max_length: 120 }, dependencies: [{ question_id: 'discovery_has_existing_website', operator: 'equals', value: 'yes_existing_website' }], mapping_destination: 'enrichment.existing_presence.website.improve' }),
    question({ id: 'discovery_website_dislikes', category_id: 'discovery', title: 'What do you dislike about the current website?', description: 'Optional factual context for a future reviewed design workflow.', answer_type: 'textarea', required: false, validation: { max_length: 1200 }, dependencies: [{ question_id: 'discovery_has_existing_website', operator: 'equals', value: 'yes_existing_website' }], mapping_destination: 'enrichment.existing_presence.website.dislikes' }),
    question({ id: 'discovery_has_shopify_store', category_id: 'discovery', title: 'Do you already have a Shopify store?', description: 'No Shopify connection is made in this phase.', answer_type: 'boolean', required: true, follow_up_question_ids: ['discovery_shopify_store_url', 'discovery_shopify_store_live', 'discovery_shopify_structure', 'discovery_shopify_intent'], mapping_destination: 'enrichment.existing_presence.shopify.status' }),
    question({ id: 'discovery_shopify_store_url', category_id: 'discovery', title: 'What is the Shopify store URL or myshopify domain?', description: 'Enter a complete URL or a myshopify domain.', answer_type: 'url_or_domain', required: true, dependencies: [{ question_id: 'discovery_has_shopify_store', operator: 'equals', value: true }], mapping_destination: 'enrichment.existing_presence.shopify.url' }),
    question({ id: 'discovery_shopify_store_live', category_id: 'discovery', title: 'Is the Shopify store live?', description: 'This is reference context only.', answer_type: 'boolean', required: true, dependencies: [{ question_id: 'discovery_has_shopify_store', operator: 'equals', value: true }], mapping_destination: 'enrichment.existing_presence.shopify.is_live' }),
    question({ id: 'discovery_shopify_structure', category_id: 'discovery', title: 'How should Calinium treat the current structure?', description: 'Select the intended level of preservation.', answer_type: 'single_choice', required: true, options: choices([['preserve_current_structure', 'Preserve the current structure'], ['redesign_structure', 'Redesign the structure'], ['optimize_current_structure', 'Optimize the current structure']]), dependencies: [{ question_id: 'discovery_has_shopify_store', operator: 'equals', value: true }], mapping_destination: 'enrichment.existing_presence.shopify.structure_preference' }),
    question({ id: 'discovery_shopify_intent', category_id: 'discovery', title: 'What do you expect from the Shopify work?', description: 'Choose the primary intent for this existing store.', answer_type: 'single_choice', required: true, options: choices([['redesign', 'Redesign'], ['migration', 'Migration'], ['optimization', 'Optimization']]), dependencies: [{ question_id: 'discovery_has_shopify_store', operator: 'equals', value: true }], mapping_destination: 'enrichment.existing_presence.shopify.intent' }),
    question({ id: 'discovery_desired_outcomes', category_id: 'discovery', title: 'What outcomes matter most?', description: 'Choose all outcomes that apply; this remains merchant intent rather than generated strategy.', answer_type: 'multiple_choice', required: true, validation: { min_items: 1, max_items: 5 }, options: choices([['launch_new_store', 'Launch a new store'], ['redesign_existing_store', 'Redesign an existing store'], ['improve_conversion', 'Improve conversion'], ['improve_brand_positioning', 'Improve brand positioning'], ['modernize_visual_identity', 'Modernize visual identity'], ['improve_mobile_experience', 'Improve mobile experience'], ['improve_navigation', 'Improve navigation'], ['improve_product_storytelling', 'Improve product storytelling'], ['prepare_for_growth', 'Prepare for growth'], ['migrate_to_shopify', 'Migrate to Shopify']]), mapping_destination: 'enrichment.desired_outcomes' }),
    question({ id: 'discovery_creative_freedom', category_id: 'discovery', title: 'How much creative freedom should Calinium have?', description: 'This creates a clear design constraint for future approved workflows.', answer_type: 'single_choice', required: true, options: choices([['preserve_existing_identity', 'Preserve existing identity'], ['refine_existing_identity', 'Refine existing identity'], ['modernize_significantly', 'Modernize significantly'], ['complete_redesign', 'Complete redesign'], ['calinium_decides', 'Calinium decides']]), mapping_destination: 'enrichment.creative_direction.creative_freedom' }),

    question({ id: 'business_brand_name', category_id: 'business', title: 'What is the brand name?', description: 'Use the name customers should see.', answer_type: 'text', required: true, validation: { min_length: 1, max_length: 120 }, mapping_destination: 'business.name' }),
    question({ id: 'business_legal_name', category_id: 'business', title: 'What is the legal business name?', description: 'Optional operational context; it is not used as storefront copy.', answer_type: 'text', required: false, validation: { max_length: 160 } }),
    question({ id: 'business_website', category_id: 'business', title: 'What is the existing website?', description: 'Optional. Supply a complete URL if one exists.', answer_type: 'url', required: false }),
    question({ id: 'business_shopify_store_url', category_id: 'business', title: 'What is the Shopify store URL?', description: 'Optional and used only as a merchant-supplied reference.', answer_type: 'url', required: false }),
    question({ id: 'business_model', category_id: 'business', title: 'What is the business model?', description: 'Choose the primary commercial model.', answer_type: 'single_choice', required: true, options: choices([['direct_to_consumer', 'Direct to consumer'], ['business_to_business', 'Business to business'], ['hybrid', 'B2B and B2C'], ['software_subscription', 'Software subscription'], ['marketplace', 'Marketplace']]), mapping_destination: 'business.model' }),
    question({ id: 'business_industry', category_id: 'business', title: 'Which industry best describes the business?', description: 'This selects an existing Calinium industry profile; choose the closest known category.', answer_type: 'single_choice', required: true, options: options(knowledge.raw.industries.items), follow_up_question_ids: ['product_apparel_categories', 'product_room_context'], mapping_destination: 'industry' }),
    question({ id: 'business_product_category', category_id: 'business', title: 'What is the primary product category?', description: 'Use a short specific category, such as leather bags or skincare.', answer_type: 'text', required: true, validation: { min_length: 1, max_length: 120 }, mapping_destination: 'subcategory' }),
    question({ id: 'business_stage', category_id: 'business', title: 'What stage is the business in?', description: 'This is interview context and does not change existing compiler rules.', answer_type: 'single_choice', required: true, options: choices([['pre_launch', 'Pre-launch'], ['operating', 'Operating'], ['replatforming', 'Replatforming']]) }),
    question({ id: 'business_store_status', category_id: 'business', title: 'Is this an existing or new store?', description: 'This helps a future host choose an appropriate onboarding path.', answer_type: 'single_choice', required: true, options: choices([['existing_store', 'Existing store'], ['new_store', 'New store']]) }),

    question({ id: 'brand_mission', category_id: 'brand', title: 'What is the brand mission?', description: 'Optional. Keep this as merchant-provided source material rather than generated copy.', answer_type: 'textarea', required: false, validation: { max_length: 2000 } }),
    question({ id: 'brand_story', category_id: 'brand', title: 'What is the brand story?', description: 'Optional. It may require merchant verification before publication.', answer_type: 'textarea', required: false, validation: { max_length: 4000 } }),
    question({ id: 'brand_personality_primary', category_id: 'brand', title: 'Which personality is primary?', description: 'Choose the strongest fit from the existing Calinium personality catalog.', answer_type: 'single_choice', required: true, options: options(knowledge.raw.personalities.items), mapping_destination: 'brand_personality.primary' }),
    question({ id: 'brand_personality_secondary', category_id: 'brand', title: 'Are there secondary personality traits?', description: 'Optional. Select up to two compatible traits.', answer_type: 'multiple_choice', required: false, validation: { max_items: 2 }, options: options(knowledge.raw.personalities.items), mapping_destination: 'brand_personality.secondary' }),
    question({ id: 'brand_values', category_id: 'brand', title: 'What values should the brand communicate?', description: 'Optional short value tags.', answer_type: 'tags', required: false, validation: { max_items: 8, max_length: 80 } }),
    question({ id: 'brand_customer_perception', category_id: 'brand', title: 'How should customers perceive the brand?', description: 'Optional perception tags.', answer_type: 'tags', required: false, validation: { max_items: 8, max_length: 80 } }),
    question({ id: 'brand_tone_of_voice', category_id: 'brand', title: 'What tone of voice fits the brand?', description: 'Optional tone tags. This is reference material, not generated copy.', answer_type: 'tags', required: false, validation: { max_items: 6, max_length: 80 } }),

    question({ id: 'audience_customer_type', category_id: 'audience', title: 'Who is the primary customer?', description: 'Describe the primary audience in the merchant’s own words.', answer_type: 'textarea', required: true, validation: { min_length: 1, max_length: 500 }, mapping_destination: 'audience.primary' }),
    question({ id: 'audience_needs', category_id: 'audience', title: 'What does this customer need from the storefront?', description: 'Add concise needs or decision drivers.', answer_type: 'tags', required: true, validation: { min_items: 1, max_items: 8, max_length: 100 }, mapping_destination: 'audience.needs' }),
    question({ id: 'audience_age_range', category_id: 'audience', title: 'What age ranges are relevant?', description: 'Optional audience research context.', answer_type: 'tags', required: false, validation: { max_items: 6, max_length: 40 } }),
    question({ id: 'audience_gender', category_id: 'audience', title: 'Is gender targeting relevant?', description: 'Optional. Choose not specified when it is not relevant.', answer_type: 'single_choice', required: false, options: choices([['not_specified', 'Not specified'], ['women', 'Women'], ['men', 'Men'], ['non_binary', 'Non-binary'], ['all_genders', 'All genders']]) }),
    question({ id: 'audience_countries', category_id: 'audience', title: 'Which countries are important?', description: 'Optional country tags.', answer_type: 'tags', required: false, validation: { max_items: 20, max_length: 80 } }),
    question({ id: 'audience_languages', category_id: 'audience', title: 'Which languages are important?', description: 'Optional language tags; this does not enable localization by itself.', answer_type: 'tags', required: false, validation: { max_items: 12, max_length: 80 } }),
    question({ id: 'audience_market_model', category_id: 'audience', title: 'Is the storefront B2C, B2B, or both?', description: 'Feature context retained in the interview session.', answer_type: 'single_choice', required: true, options: choices([['b2c', 'B2C'], ['b2b', 'B2B'], ['hybrid', 'Both B2C and B2B']]) }),
    question({ id: 'audience_price_positioning', category_id: 'audience', title: 'What is the market positioning?', description: 'Choose the price and presentation position.', answer_type: 'single_choice', required: true, options: choices([['luxury', 'Luxury'], ['premium', 'Premium'], ['mid_market', 'Mid-market'], ['budget', 'Budget']]), mapping_destination: 'catalog.price_positioning' }),

    question({ id: 'product_types', category_id: 'products', title: 'What product types are sold?', description: 'Add concise product-type tags.', answer_type: 'tags', required: true, validation: { min_items: 1, max_items: 20, max_length: 100 }, mapping_destination: 'catalog.product_types' }),
    question({ id: 'product_collections', category_id: 'products', title: 'Which collections matter most?', description: 'Optional collection names. This does not select Shopify collections.', answer_type: 'tags', required: false, validation: { max_items: 20, max_length: 120 } }),
    question({ id: 'product_sku_count', category_id: 'products', title: 'How many products or SKUs are currently offered?', description: 'Use a whole number.', answer_type: 'number', required: true, validation: { minimum: 0, integer: true }, mapping_destination: 'catalog.product_count' }),
    question({ id: 'product_average_selling_price', category_id: 'products', title: 'What is the typical selling price?', description: 'Optional number only; currency and locale are provided by the future host.', answer_type: 'currency', required: false, validation: { minimum: 0 } }),
    question({ id: 'product_hero_products', category_id: 'products', title: 'Which products are hero products?', description: 'Optional names only. This does not select Shopify products.', answer_type: 'tags', required: false, validation: { max_items: 12, max_length: 120 } }),
    question({ id: 'product_delivery', category_id: 'products', title: 'Are products physical, digital, or both?', description: 'This controls relevant follow-up questions.', answer_type: 'multiple_choice', required: true, validation: { min_items: 1, max_items: 2 }, options: choices([['physical', 'Physical products'], ['digital', 'Digital products']]), follow_up_question_ids: ['product_shipping_needs', 'product_digital_delivery_model'] }),
    question({ id: 'product_has_variants', category_id: 'products', title: 'Do products have variants?', description: 'Examples include size, colour, format, or plan.', answer_type: 'boolean', required: true, mapping_destination: 'catalog.has_variants' }),
    question({ id: 'product_apparel_categories', category_id: 'products', title: 'Which apparel categories are relevant?', description: 'Optional apparel-specific context shown only for fashion industries.', answer_type: 'tags', required: false, validation: { max_items: 12, max_length: 80 }, dependencies: [{ question_id: 'business_industry', operator: 'includes', value: ['fashion', 'luxury_fashion'] }] }),
    question({ id: 'product_room_context', category_id: 'products', title: 'Which rooms or spaces are relevant?', description: 'Optional room-inspiration context shown only for furniture and home industries.', answer_type: 'tags', required: false, validation: { max_items: 12, max_length: 80 }, dependencies: [{ question_id: 'business_industry', operator: 'includes', value: ['furniture', 'home'] }] }),
    question({ id: 'product_shipping_needs', category_id: 'products', title: 'What shipping considerations are important?', description: 'Optional physical-product context. It is hidden for digital-only catalogs.', answer_type: 'tags', required: false, validation: { max_items: 10, max_length: 100 }, dependencies: [{ question_id: 'product_delivery', operator: 'includes', value: 'physical' }] }),
    question({ id: 'product_digital_delivery_model', category_id: 'products', title: 'How are digital products delivered?', description: 'Optional digital-product context.', answer_type: 'single_choice', required: false, options: choices([['download', 'Download'], ['subscription_access', 'Subscription access'], ['license', 'License'], ['service_access', 'Service access']]), dependencies: [{ question_id: 'product_delivery', operator: 'includes', value: 'digital' }] }),

    question({ id: 'design_preferred_style', category_id: 'design', title: 'Which visual styles feel right?', description: 'Select existing Calinium design-language preferences; references never instruct Calinium to copy another design.', answer_type: 'multiple_choice', required: true, validation: { min_items: 1, max_items: 3 }, options: options(knowledge.raw.designLanguages.items), mapping_destination: 'preferences.design_languages' }),
    question({ id: 'design_color_strategy', category_id: 'design', title: 'Which colour strategies feel right?', description: 'Optional existing Calinium colour-strategy preferences.', answer_type: 'multiple_choice', required: false, validation: { max_items: 2 }, options: options(knowledge.raw.colors.items), mapping_destination: 'preferences.color_strategies' }),
    question({ id: 'design_image_style', category_id: 'design', title: 'Which image styles fit the brand?', description: 'Optional existing Calinium image-style preferences.', answer_type: 'multiple_choice', required: false, validation: { max_items: 3 }, options: options(knowledge.raw.images.items), mapping_destination: 'preferences.image_styles' }),
    question({ id: 'design_content_density', category_id: 'design', title: 'How much content should the first page carry?', description: 'Choose a density preference, not a copy quantity.', answer_type: 'single_choice', required: true, options: choices([['low', 'Low'], ['medium', 'Medium'], ['high', 'High']]), mapping_destination: 'preferences.content_density' }),
    question({ id: 'design_page_type', category_id: 'design', title: 'Which page should Calinium plan first?', description: 'Choose an existing page blueprint.', answer_type: 'single_choice', required: true, options: options(knowledge.raw.blueprints.items), mapping_destination: 'preferences.page_type' }),
    question({ id: 'design_existing_color', category_id: 'design', title: 'Is there an existing primary brand colour?', description: 'Optional HEX colour reference. It does not alter theme settings automatically; Not available is accepted.', answer_type: 'color', required: false, validation: { allow_not_available: true } }),
    question({ id: 'design_existing_typography', category_id: 'design', title: 'Is there existing typography to preserve?', description: 'Optional reference only; asset and licensing verification remain merchant responsibilities. Not available is accepted.', answer_type: 'text', required: false, validation: { max_length: 160, allow_not_available: true } }),
    question({ id: 'design_inspiration_image', category_id: 'design', title: 'Is inspiration imagery available?', description: 'Optional upload placeholder. A future host may collect the file; the interview stores no media.', answer_type: 'image_placeholder', required: false }),
    question({ id: 'design_visual_personality', category_id: 'design', title: 'Which visual traits should the storefront express?', description: 'Optional structured traits, such as warm, restrained, confident, or contemporary.', answer_type: 'tags', required: false, validation: { max_items: 8, max_length: 80 }, mapping_destination: 'enrichment.creative_direction.visual_personality' }),
    question({ id: 'design_emotional_response', category_id: 'design', title: 'How should the storefront make customers feel?', description: 'Optional emotional-response tags; do not use these as claims about customers.', answer_type: 'tags', required: false, validation: { max_items: 6, max_length: 80 }, mapping_destination: 'enrichment.creative_direction.emotional_response' }),
    question({ id: 'design_image_emphasis', category_id: 'design', title: 'How image-led should the storefront feel?', description: 'Choose a presentation preference.', answer_type: 'single_choice', required: false, options: choices([['product_first', 'Product-first'], ['balanced', 'Balanced'], ['editorial_image_led', 'Editorial and image-led']]), mapping_destination: 'enrichment.creative_direction.image_emphasis' }),
    question({ id: 'design_motion_preference', category_id: 'design', title: 'What level of motion feels right?', description: 'This is a merchant preference, subject to accessibility safeguards.', answer_type: 'single_choice', required: false, options: choices([['minimal', 'Minimal'], ['restrained', 'Restrained'], ['expressive', 'Expressive']]), mapping_destination: 'enrichment.creative_direction.motion_preference' }),
    question({ id: 'design_tradition_direction', category_id: 'design', title: 'Should the visual direction feel traditional or contemporary?', description: 'Optional directional context.', answer_type: 'single_choice', required: false, options: choices([['traditional', 'Traditional'], ['balanced', 'Balanced'], ['contemporary', 'Contemporary']]), mapping_destination: 'enrichment.creative_direction.tradition_direction' }),

    question({ id: 'references_favorite_websites', category_id: 'brand_references', title: 'Which websites are useful references?', description: 'Optional URL tags. References are kept separate from design decisions and must not be copied.', answer_type: 'tags', required: false, validation: { max_items: 10, max_length: 240 } }),
    question({ id: 'references_favorite_brands', category_id: 'brand_references', title: 'Which brands are useful references?', description: 'Optional brand-name tags; Calinium records inspiration, not copied design.', answer_type: 'tags', required: false, validation: { max_items: 12, max_length: 120 } }),
    question({ id: 'references_competitors', category_id: 'brand_references', title: 'Who are the competitors?', description: 'Optional competitor-name tags retained separately from profile decisions.', answer_type: 'tags', required: false, validation: { max_items: 12, max_length: 120 } }),
    question({ id: 'references_inspiration_stores', category_id: 'brand_references', title: 'Which stores are inspirational?', description: 'Optional store-name tags. Do not use them as instructions to copy layouts or claims.', answer_type: 'tags', required: false, validation: { max_items: 12, max_length: 120 } }),
    question({ id: 'references_inspiration_entries', category_id: 'brand_references', title: 'Which websites or brands inspire you?', description: 'Add each reference separately. Calinium stores the reason and visual traits without copying the reference.', answer_type: 'reference_list', required: false, validation: { max_items: 8 }, ui: { component: 'reference_list', reference_kind: 'inspiration', allow_screenshot: true }, mapping_destination: 'enrichment.inspiration_references' }),
    question({ id: 'references_competitor_entries', category_id: 'brand_references', title: 'Which businesses compete with you?', description: 'Competitor context is distinct from inspiration. Record what they do well and what you want to avoid.', answer_type: 'reference_list', required: false, validation: { max_items: 8 }, ui: { component: 'reference_list', reference_kind: 'competitor', allow_screenshot: true }, mapping_destination: 'enrichment.competitor_references' }),

    question({ id: 'features_requested', category_id: 'features', title: 'Which features are desired?', description: 'Select desired capabilities. Selection is an intent signal, not proof that the theme currently supports it.', answer_type: 'multiple_choice', required: false, validation: { max_items: 12 }, options: choices([['wishlist', 'Wishlist'], ['subscriptions', 'Subscriptions'], ['product_bundles', 'Product bundles'], ['reviews', 'Reviews'], ['mega_menu', 'Mega menu'], ['quick_buy', 'Quick buy'], ['sticky_cart', 'Sticky cart'], ['multi_language', 'Multi-language'], ['multi_currency', 'Multi-currency'], ['b2b', 'B2B'], ['wholesale', 'Wholesale']]) }),

    question({ id: 'content_available_assets', category_id: 'content', title: 'Which approved assets are available?', description: 'Select only assets the merchant has and is allowed to use, or choose Not available.', answer_type: 'multiple_choice', required: false, validation: { max_items: 12, allow_not_available: true }, options: choices([['logo', 'Logo'], ['product_media', 'Product photography'], ['lifestyle_media', 'Lifestyle photography'], ['founder_portrait', 'Founder portrait'], ['craft_media', 'Craft or process media'], ['team_portraits', 'Team portraits'], ['authentic_gallery_media', 'Authentic gallery media'], ['video', 'Video'], ['not_available', 'Not available']]), mapping_destination: 'assets.available' }),
    question({ id: 'content_asset_notes', category_id: 'content', title: 'Are there notes about available or missing assets?', description: 'Optional factual notes only.', answer_type: 'textarea', required: false, validation: { max_length: 1000 }, mapping_destination: 'assets.notes' }),
    question({ id: 'content_existing_copy', category_id: 'content', title: 'Is approved existing copy available?', description: 'This is a source-material indicator only; the interview does not generate copy.', answer_type: 'boolean', required: false }),
    question({ id: 'content_logo_upload', category_id: 'content', title: 'Is a logo file ready to provide?', description: 'Optional upload placeholder. A future host may collect the file; Not available is accepted.', answer_type: 'upload_placeholder', required: false, validation: { allow_not_available: true } }),
    question({ id: 'content_photography_upload', category_id: 'content', title: 'Is approved photography ready to provide?', description: 'Optional image placeholder for existing photography; Not available is accepted.', answer_type: 'image_placeholder', required: false, validation: { allow_not_available: true } }),
    question({ id: 'content_contact_email', category_id: 'content', title: 'What is the primary implementation contact email?', description: 'Optional operational contact; not storefront content.', answer_type: 'email', required: false }),
    question({ id: 'content_logo_status', category_id: 'content', title: 'Do you already have a logo?', description: 'Choose the current state. Calinium will not generate a logo in this phase.', answer_type: 'single_choice', required: true, options: choices([['upload_logo', 'Upload logo'], ['use_existing_website_logo_later', 'Use existing website logo later'], ['no_logo', 'No logo'], ['need_logo_support', 'Need logo support']]), follow_up_question_ids: ['content_logo_asset'], mapping_destination: 'enrichment.brand_assets.logo_status' }),
    question({ id: 'content_logo_asset', category_id: 'content', title: 'Upload your logo', description: 'PNG, JPEG, or WebP logos can be stored in the secure project Asset Library.', answer_type: 'asset_reference', required: true, dependencies: [{ question_id: 'content_logo_status', operator: 'equals', value: 'upload_logo' }], ui: { component: 'asset_uploader', asset_type: 'logo', accepted_types: ['image/png', 'image/jpeg', 'image/webp'] }, mapping_destination: 'enrichment.brand_assets.logo_asset_id' }),
    question({ id: 'content_color_source', category_id: 'content', title: 'How would you like to define your colours?', description: 'Calinium never automatically replaces merchant-approved colours.', answer_type: 'single_choice', required: true, options: choices([['choose_manually', 'Choose manually'], ['extract_from_logo', 'Extract from logo'], ['use_existing_brand', 'Use an existing brand palette'], ['use_current_website_later', 'Use current website later'], ['let_calinium_suggest', 'Let Calinium suggest later']]), follow_up_question_ids: ['content_manual_color_palette', 'content_extracted_color_palette'], mapping_destination: 'enrichment.brand_colors.source' }),
    question({ id: 'content_manual_color_palette', category_id: 'content', title: 'Define the colour palette', description: 'Choose primary, secondary, accent, background, and text colours. Contrast feedback is informative.', answer_type: 'color_palette', required: true, dependencies: [{ question_id: 'content_color_source', operator: 'includes', value: ['choose_manually', 'use_existing_brand'] }], ui: { component: 'color_palette', palette_mode: 'manual' }, mapping_destination: 'enrichment.brand_colors.palette' }),
    question({ id: 'content_extracted_color_palette', category_id: 'content', title: 'Review colours extracted from the logo', description: 'Select a supported PNG logo, review the suggestions, and explicitly approve them before use.', answer_type: 'color_palette', required: true, dependencies: [{ question_id: 'content_color_source', operator: 'equals', value: 'extract_from_logo' }], ui: { component: 'color_palette', palette_mode: 'extracted', source_question_id: 'content_logo_asset' }, mapping_destination: 'enrichment.brand_colors.palette' }),
    question({ id: 'content_typography_preference', category_id: 'content', title: 'Do you have typography preferences?', description: 'Store font names as references only; this phase does not upload or distribute font files.', answer_type: 'single_choice', required: true, options: choices([['no_preference', 'No preference'], ['existing_brand_fonts', 'Existing brand fonts'], ['choose_from_categories', 'Choose from categories'], ['let_calinium_suggest', 'Let Calinium suggest']]), follow_up_question_ids: ['content_heading_typography', 'content_body_typography', 'content_font_references'], mapping_destination: 'enrichment.typography.preference' }),
    question({ id: 'content_heading_typography', category_id: 'content', title: 'Which heading styles fit the brand?', description: 'Optional typographic direction.', answer_type: 'multiple_choice', required: false, validation: { max_items: 3 }, options: choices([['serif', 'Serif'], ['sans_serif', 'Sans-serif'], ['display', 'Display'], ['editorial', 'Editorial'], ['geometric', 'Geometric'], ['humanist', 'Humanist'], ['traditional', 'Traditional'], ['modern', 'Modern'], ['minimal', 'Minimal']]), dependencies: [{ question_id: 'content_typography_preference', operator: 'includes', value: ['choose_from_categories', 'existing_brand_fonts'] }], mapping_destination: 'enrichment.typography.heading_styles' }),
    question({ id: 'content_body_typography', category_id: 'content', title: 'Which body-text styles fit the brand?', description: 'Optional typographic direction.', answer_type: 'multiple_choice', required: false, validation: { max_items: 3 }, options: choices([['serif', 'Serif'], ['sans_serif', 'Sans-serif'], ['editorial', 'Editorial'], ['geometric', 'Geometric'], ['humanist', 'Humanist'], ['traditional', 'Traditional'], ['modern', 'Modern'], ['minimal', 'Minimal']]), dependencies: [{ question_id: 'content_typography_preference', operator: 'includes', value: ['choose_from_categories', 'existing_brand_fonts'] }], mapping_destination: 'enrichment.typography.body_styles' }),
    question({ id: 'content_font_references', category_id: 'content', title: 'What existing font names should be considered?', description: 'Optional reference names only. Do not upload licensed font files.', answer_type: 'tags', required: false, validation: { max_items: 6, max_length: 120 }, dependencies: [{ question_id: 'content_typography_preference', operator: 'equals', value: 'existing_brand_fonts' }], mapping_destination: 'enrichment.typography.font_references' }),
    question({ id: 'content_asset_readiness', category_id: 'content', title: 'Which existing source materials are ready?', description: 'Select materials that exist today. You can upload now, add later, or mark them unavailable without blocking the interview.', answer_type: 'multiple_choice', required: false, validation: { max_items: 10 }, options: choices([['product_photography', 'Product photography'], ['lifestyle_photography', 'Lifestyle photography'], ['campaign_photography', 'Campaign photography'], ['video', 'Video'], ['copywriting', 'Copywriting'], ['brand_guidelines', 'Brand guidelines'], ['testimonials', 'Testimonials'], ['press_features', 'Press features'], ['icons_or_illustrations', 'Icons or illustrations']]), mapping_destination: 'enrichment.available_content_assets.declared' }),
    question({ id: 'content_asset_next_step', category_id: 'content', title: 'What would you like to do with available assets?', description: 'Choose a non-binding readiness state for this stage.', answer_type: 'single_choice', required: false, options: choices([['upload_now', 'Upload now'], ['add_later', 'Add later'], ['not_available', 'Not available']]), mapping_destination: 'enrichment.asset_readiness.next_step' }),

    question({ id: 'goals_primary', category_id: 'goals', title: 'What are the primary storefront goals?', description: 'Choose the outcomes that matter most.', answer_type: 'multiple_choice', required: true, validation: { min_items: 1, max_items: 4 }, options: choices([['increase_conversions', 'Increase conversions'], ['luxury', 'Luxury presentation'], ['story_first', 'Storytelling'], ['fast_shopping', 'Fast shopping'], ['brand_awareness', 'Brand awareness'], ['seo', 'SEO'], ['wholesale', 'Wholesale'], ['international_expansion', 'International expansion'], ['trust_first', 'Build trust'], ['product_first', 'Product discovery'], ['education_first', 'Educate customers']]), mapping_destination: 'goals.primary' }),
    question({ id: 'goals_secondary', category_id: 'goals', title: 'Are there secondary storefront goals?', description: 'Optional supporting outcomes.', answer_type: 'multiple_choice', required: false, validation: { max_items: 4 }, options: choices([['increase_conversions', 'Increase conversions'], ['luxury', 'Luxury presentation'], ['story_first', 'Storytelling'], ['fast_shopping', 'Fast shopping'], ['brand_awareness', 'Brand awareness'], ['seo', 'SEO'], ['wholesale', 'Wholesale'], ['international_expansion', 'International expansion'], ['trust_first', 'Build trust'], ['product_first', 'Product discovery'], ['education_first', 'Educate customers']]), mapping_destination: 'goals.secondary' })
  ];
  return {
    version: 1,
    catalog_version: CATALOG_VERSION,
    branching_version: BRANCHING_VERSION,
    interview_id: INTERVIEW_ID,
    title: 'Calinium merchant interview',
    description: 'A structured, merchant-confirmed intent layer that maps compatible answers to the canonical Calinium merchant profile.',
    categories,
    questions
  };
}

module.exports = { getQuestionCatalog };
