import { t } from '../../lib/i18n';

function Item({ title, children }) { return <section className="profile-section"><h2>{title}</h2>{children}</section>; }
function List({ values = [] }) { return values.length ? <ul>{values.map((value) => <li key={value}>{value}</li>)}</ul> : <p>{t('profile_view.not_provided')}</p>; }
export function MerchantProfileScreen({ projectData, navigate }) {
  const profile = projectData?.merchant_profile?.profile;
  if (!profile) return <section className="dashboard-loading"><p>{t('project.profile_pending')}</p></section>;
  const enrichment = profile.enrichment || {};
  return <section className="merchant-profile-view"><header className="dashboard-page-heading"><div><p className="eyebrow">{t('profile_view.eyebrow')}</p><h1>{profile.business.name}</h1><p>{t('profile_view.description')}</p></div><button className="button button--quiet" type="button" onClick={() => navigate(`/projects/${projectData.project.id}/interview`)}>{t('profile_view.edit')}</button></header><div className="profile-section-grid"><Item title={t('profile_view.business')}><dl><dt>{t('profile_view.industry')}</dt><dd>{profile.industry}</dd><dt>{t('profile_view.stage')}</dt><dd>{enrichment.discovery?.business_stage || t('profile_view.not_provided')}</dd><dt>{t('profile_view.model')}</dt><dd>{profile.business.model}</dd></dl></Item><Item title={t('profile_view.outcomes')}><List values={enrichment.desired_outcomes || profile.goals.primary} /></Item><Item title={t('profile_view.existing_presence')}><dl><dt>{t('profile_view.website')}</dt><dd>{enrichment.existing_presence?.website?.url || t('profile_view.not_provided')}</dd><dt>{t('profile_view.shopify')}</dt><dd>{enrichment.existing_presence?.shopify?.url || t('profile_view.not_provided')}</dd></dl></Item><Item title={t('profile_view.brand_direction')}><dl><dt>{t('profile_view.freedom')}</dt><dd>{enrichment.creative_direction?.creative_freedom || t('profile_view.not_provided')}</dd><dt>{t('profile_view.colors')}</dt><dd>{enrichment.brand_colors?.palette?.colors?.primary || t('profile_view.not_provided')}</dd><dt>{t('profile_view.typography')}</dt><dd>{enrichment.typography?.preference || t('profile_view.not_provided')}</dd></dl></Item><Item title={t('profile_view.assets')}><List values={enrichment.available_content_assets?.declared || profile.assets.available} /><button className="text-button" type="button" onClick={() => navigate(`/projects/${projectData.project.id}/assets`)}>{t('profile_view.view_assets')}</button></Item><Item title={t('profile_view.inspiration')}><List values={(enrichment.inspiration_references || []).map((reference) => reference.name)} /></Item><Item title={t('profile_view.competitors')}><List values={(enrichment.competitor_references || []).map((reference) => reference.name)} /></Item></div><details className="profile-debug"><summary>{t('profile_view.raw_json')}</summary><pre className="profile-json">{JSON.stringify(profile, null, 2)}</pre></details><button className="text-button" type="button" onClick={() => navigate(`/projects/${projectData.project.id}`)}>{t('profile_view.back_to_project')}</button></section>;
}
