import { useEffect, useState } from 'react';
import { t } from '../../lib/i18n';

export function SettingsScreen({ service, account }) {
  const [data, setData] = useState(null);
  const [saved, setSaved] = useState(null);
  const [error, setError] = useState(null);
  useEffect(() => { let mounted = true; Promise.all([service.account(), service.preferences()]).then(([profile, preferences]) => { if (mounted) setData({ ...profile, preferences: preferences.preferences }); }).catch((reason) => { if (mounted) setError(reason.message); }); return () => { mounted = false; }; }, [service]);
  if (!data) return <section className="dashboard-loading" aria-busy="true"><p>{error || t('app.loading')}</p></section>;
  const organization = data.organizations[0]?.organization;
  const save = async (kind, input) => { setError(null); try { if (kind === 'profile') await service.updateAccount(input); if (kind === 'organization') await service.updateOrganization(input); if (kind === 'preferences') await service.updatePreferences(input); setSaved(kind); } catch (reason) { setError(reason.message); } };
  return <section className="settings-page"><header className="dashboard-page-heading"><div><p className="eyebrow">{t('settings.eyebrow')}</p><h1>{t('settings.title')}</h1><p>{t('settings.description')}</p></div></header>{error && <p className="form-error" role="alert">{error}</p>}{saved && <p className="success-message" role="status">{t('settings.saved')}</p>}<section className="settings-card"><h2>{t('settings.profile')}</h2><form onSubmit={(event) => { event.preventDefault(); save('profile', { full_name: event.currentTarget.full_name.value }); }}><label>{t('auth.full_name')}<input name="full_name" defaultValue={account.full_name || ''} required /></label><button className="button button--quiet" type="submit">{t('settings.save')}</button></form></section><section className="settings-card"><h2>{t('settings.organization')}</h2><form onSubmit={(event) => { event.preventDefault(); save('organization', { name: event.currentTarget.name.value }); }}><label>{t('settings.organization_name')}<input name="name" defaultValue={organization?.name || ''} required /></label><button className="button button--quiet" type="submit">{t('settings.save')}</button></form></section><section className="settings-card"><h2>{t('settings.preferences')}</h2><form onSubmit={(event) => { event.preventDefault(); save('preferences', { locale: event.currentTarget.locale.value }); }}><label>{t('settings.locale')}<select name="locale" defaultValue={data.preferences.locale}><option value="en">{t('settings.english')}</option></select></label><button className="button button--quiet" type="submit">{t('settings.save')}</button></form></section><section className="settings-card settings-card--locked"><h2>{t('settings.security')}</h2><p>{t('settings.security_description')}</p></section><section className="settings-card settings-card--locked"><h2>{t('settings.shopify')}</h2><p>{t('settings.shopify_description')}</p></section></section>;
}
