import { useMemo } from 'react';
import { t } from '../../lib/i18n';
import { StatusBadge } from './StatusBadge';

const merchantTypes = ['product', 'collection', 'menu', 'file', 'product_media', 'theme'];

export function ShopifyResourceApprovalList({ connection, resources, onDecision, onRevoke, pending }) {
  const grouped = useMemo(() => merchantTypes.map((type) => ({ type, items: resources.filter((entry) => entry.resource.resource_type === type) })).filter((group) => group.items.length), [resources]);
  if (!connection || connection.connection_status !== 'ready') return <p className="resource-plan-note">{t('creative_director.resources.shopify.sync_before_approval')}</p>;
  if (!grouped.length) return <p className="resource-plan-note">{t('creative_director.resources.shopify.empty_resources')}</p>;
  return <section className="shopify-resource-review" aria-labelledby="shopify-resource-review-title"><div><h2 id="shopify-resource-review-title">{t('creative_director.resources.shopify.review_title')}</h2><p>{t('creative_director.resources.shopify.review_description')}</p></div>{grouped.map((group) => <section key={group.type} className="shopify-resource-review__group" aria-labelledby={`shopify-group-${group.type}`}><h3 id={`shopify-group-${group.type}`}>{t(`creative_director.resources.kind.${group.type}`)}</h3><ul>{group.items.map(({ resource, approval }) => { const decisionDisabled = pending || resource.availability_status !== 'available' || !resource.approval_eligible; return <li key={resource.id}><div>{resource.preview_url ? <img src={resource.preview_url} alt="" loading="lazy" /> : <span className="shopify-resource-review__placeholder" aria-hidden="true" />}<div><strong>{resource.display_title}</strong><small>{resource.availability_status === 'available' ? t('creative_director.resources.shopify.available') : t('creative_director.resources.shopify.unavailable')}</small>{resource.resource_type === 'theme' ? <small>{t(`shopify_live.preview_eligibility.${resource.preview_eligibility || 'missing-theme'}`)}</small> : null}</div></div><div className="shopify-resource-review__actions"><StatusBadge status={approval?.approval_status || 'pending'} />{approval?.approval_status === 'approved' ? <button className="text-button" type="button" onClick={() => onRevoke(resource.id)} disabled={pending}>{t('creative_director.resources.shopify.revoke')}</button> : <><button className="button button--quiet button--compact" type="button" onClick={() => onDecision(resource.id, 'rejected')} disabled={decisionDisabled}>{t('creative_director.resources.shopify.reject')}</button><button className="button button--primary button--compact" type="button" onClick={() => onDecision(resource.id, 'approved')} disabled={decisionDisabled}>{t('creative_director.resources.shopify.approve')}</button></>}</div></li>; })}</ul></section>)}</section>;
}
