import { useState } from 'react';
import { t } from '../../lib/i18n';

function blankReference() { return { name: '', url: '', reason: '', traits: [], specific_focus: '', screenshot_asset_id: null, market_relationship: '' }; }
export function ReferenceListEditor({ question, answer, assetService, onCommit }) {
  const [references, setReferences] = useState(Array.isArray(answer) ? answer : []); const [error, setError] = useState(null);
  const update = (index, patch) => { const next = references.map((reference, itemIndex) => itemIndex === index ? { ...reference, ...patch } : reference); setReferences(next); onCommit(question.id, next); };
  const add = () => { if (references.length >= (question.validation.max_items || 8)) return; const next = [...references, blankReference()]; setReferences(next); onCommit(question.id, next); };
  const uploadScreenshot = async (index, file) => { if (!file) return; setError(null); try { const result = await assetService.uploadAsset({ file, assetType: question.ui?.reference_kind === 'competitor' ? 'competitor_screenshot' : 'inspiration_screenshot', displayTitle: file.name }); update(index, { screenshot_asset_id: result.asset.id }); } catch (reason) { setError(reason.message); } };
  return <div className="reference-list">{references.map((reference, index) => <article className="reference-card" key={`${reference.name}-${index}`}><div className="reference-card__header"><h3>{t('references.entry', { number: index + 1 })}</h3><button type="button" className="text-button" onClick={() => { const next = references.filter((_, itemIndex) => itemIndex !== index); setReferences(next); onCommit(question.id, next); }}>{t('references.remove')}</button></div><label><span>{t('references.name')}</span><input value={reference.name} onChange={(event) => update(index, { name: event.target.value })} /></label><label><span>{t('references.url')}</span><input type="url" value={reference.url || ''} onChange={(event) => update(index, { url: event.target.value })} /></label><label><span>{t('references.reason')}</span><textarea value={reference.reason || ''} onChange={(event) => update(index, { reason: event.target.value })} /></label><label><span>{t('references.traits')}</span><input value={(reference.traits || []).join(', ')} onChange={(event) => update(index, { traits: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} /></label>{question.ui?.reference_kind === 'competitor' && <label><span>{t('references.relationship')}</span><input value={reference.market_relationship || ''} onChange={(event) => update(index, { market_relationship: event.target.value })} /></label>}<label><span>{t('references.screenshot')}</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => uploadScreenshot(index, event.target.files?.[0])} />{reference.screenshot_asset_id && <small>{t('references.screenshot_added')}</small>}</label></article>)}<button type="button" className="button button--quiet" onClick={add}>{t('references.add')}</button>{error && <p className="form-error" role="alert">{error}</p>}</div>;
}
